### PR TITLE
Initial implementation for acpush

### PR DESCRIPTION
**Pull request by cgonyeo**
Currently supports performing meta discovery to find appropriate endpoint, and pushing provided image and signature to the server. Relies on rkt's config files for authentication.

### CODE REVIEW

**Comment by cgonyeo** [comment]
Implements client side of https://github.com/appc/spec/issues/418

**Comment by cgonyeo** [comment]
Should be ready for another pass

**Comment by cgonyeo** [comment]
Another pass on this would be great.

**Comment by jonboulle** [comment]
@steveeJ review?

**Comment by cgonyeo** [comment]
```
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.4.5
$ rake
rake aborted!
```

Perhaps disable travis on this repo for the time being?

**Comment by jonboulle** [comment]
changed travis to only build if .travis.yml is supplied

**Comment by cgonyeo** [comment]
Removed the binary, reformatted the README to have one sentence per line, and tweaked the build instructions in the REAME. Should be ready for another pass @steveeJ.

**Comment by cgonyeo** [comment]
ping?

**Comment by steveej** [comment]
LGTM if it works

**Comment by philips** [comment]
The idea is that this will be a library for use by rkt, right?

**Comment by cgonyeo** [comment]
Yes, if rkt gains the ability to export an exited container's rootfs. I think it makes more sense to put it in acbuild, if only because that's the tool that modifies images, and pushing unmodified images doesn't sound particularly exciting.

**Comment by philips** [comment]
I think rkt should have push/pull because it makes it symmetric. I see the
process as build with your build tool, fetch/import into rkt, push from rkt.

**Pull request merged**
